services:
  emb:
    image: "kemingy/mosec-emb-cpu"
    environment:
      - MOSEC_TIMEOUT=30000
    ports:
      - "8080:8000"

  pg:
    image: "tensorchord/pgvecto-rs:pg15-v0.2.0"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "/tmp/qtext_pgdata:/var/lib/postgresql/data"

  colbert:
    image: "kemingy/colbert-highlight"
    ports:
      - "8081:8000"

  encoder:
    image: "kemingy/cross-encoder"
    ports:
      - "8082:8000"

  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pg
      - emb
      - colbert
