services:
  emb:
    image: "kemingy/mosec-emb-cpu"
    environment:
      - MOSEC_PORT=8080
      - MOSEC_TIMEOUT=30000
    ports:
      - "8080:8080"

  pg:
    image: "tensorchord/pgvecto-rs:pg15-v0.2.0"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "/tmp/pgdata:/var/lib/postgresql/data"

  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pg
      - emb
